name: README Stats and Activity Updater
on:
  schedule:
    - cron: '0 21 * * MON'  # Monday 21:00 UTC / TR 24:00
  workflow_dispatch:        # Manual trigger

jobs:
  update-readme:
    name: Update README Stats and Activities
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Stats Values and Update README
        uses: teoxoy/profile-readme-stats@master
        with:
          token: ${{ secrets.STATS }}

      - name:  Get Latest Activities (single-commit authority)
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 20