name: Readme Stat Updater
on:
  schedule:
    - cron: '0 0 * * *'    # It works every day at midnight UTC (00:00)
  workflow_dispatch:       # Manually trigger the workflow
jobs:
  update-readme:
    name: Update README with PRs and Activities
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest Activities
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: KaganCanSit
          COMMIT_NAME: Github Activity Readme
          COMMIT_MSG: "README Contribution and Activity Update"
          MAX_LINES: 25
          TARGET_FILE: README.md