name: Readme Activity Updater
on:
  schedule:
    - cron: '0 0 * * *'    # It works every day at midnight UTC (00:00)
  workflow_dispatch:       # Manually trigger the workflow
jobs:
  update-readme:
    name: Update README Activities Area
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest Activities with GitHub Activity Readme
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Readme activity check and update [bot]"
          MAX_LINES: 15
          COMMIT_NAME: GitHub Activity - Readme Update [bot]