name: Readme Stat Updater

on:
push:
  branches:
    - main
    - feature-add-workflow-github-stats
  schedule:
    - cron: '0 0 * * *'  # It works every day at 00:00
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Latest 10 Pull Requests
        uses: actions/github-script@v6
        id: fetch_prs
        with:
          script: |
            const { data: events } = await github.activity.listPublicEventsForUser({
              username: 'KaganCanSit',
              per_page: 100
            });
            const prs = events.filter(e => e.type === 'PullRequestEvent').slice(0, 10);
            const prList = prs.map(pr => `- [${pr.payload.pull_request.title}](${pr.payload.pull_request.html_url})`).join('\n');
            return prList;

      - name: Get Latest 10 Activities Without Pull Requests
        uses: actions/github-script@v6
        id: fetch_activities
        with:
          script: |
            const { data: events } = await github.activity.listPublicEventsForUser({
              username: 'KaganCanSit',
              per_page: 100
            });
            const activities = events.filter(e => e.type !== 'PullRequestEvent').slice(0, 10);
            const activityList = activities.map(act => {
              let desc = '';
              switch(act.type) {
                case 'IssuesEvent':
                  desc = `Issue: [${act.payload.issue.title}](${act.payload.issue.html_url})`;
                  break;
                case 'IssueCommentEvent':
                  desc = `Commented on Issue: [${act.payload.issue.title}](${act.payload.issue.html_url})`;
                  break;
                case 'PushEvent':
                  desc = `Pushed to [${act.repo.name}](https://github.com/${act.repo.name})`;
                  break;
                case 'WatchEvent':
                  desc = `Starred [${act.repo.name}](https://github.com/${act.repo.name})`;
                  break;
                default:
                  desc = `${act.type} on [${act.repo.name}](https://github.com/${act.repo.name})`;
              }
              return `- ${desc}`;
            }).join('\n');
            return activityList;

      - name: Update README.md File
        run: |
          PR_SECTION="${{ steps.fetch_prs.outputs.result }}"
          ACTIVITY_SECTION="${{ steps.fetch_activities.outputs.result }}"
          sed -i '/<!--START_SECTION:pr-->/,/<!--END_SECTION:pr-->/c\<!--START_SECTION:pr-->\n'"$PR_SECTION"'\n<!--END_SECTION:pr-->' README.md
          sed -i '/<!--START_SECTION:activity-->/,/<!--END_SECTION:activity-->/c\<!--START_SECTION:activity-->\n'"$ACTIVITY_SECTION"'\n<!--END_SECTION:activity-->' README.md

      - name: Değişiklikleri Commit Et ve Pushla
        uses: EndBug/add-and-commit@v9
        with:
          message: ":memo: README Contribitions and Activity Updated"
          add: 'README.md'
