name: README Stats and Activity Updater
on:
  schedule:
    - cron: '30 1 * * *'  # 1:30 UTC
  workflow_dispatch:      # Manual trigger
    inputs:
      update_type:
        description: 'What to update'
        required: false
        default: 'both'
        type: choice
        options:
          - both
          - stats
          - activity

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Hash BEFORE (README)
        id: hash_before
        run: |
          echo "val=$(sha256sum README.md | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"

      - name: Update Stats in README
        uses: teoxoy/profile-readme-stats@master
        with:
          token: ${{ secrets.STATS }}

      - name: Update Activity in README
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 20
          # COMMIT_MSG, COMMIT_NAME, COMMIT_EMAIL not give (don't want commit)

      - name: Hash AFTER (README)
        id: hash_after
        run: |
          echo "val=$(sha256sum README.md | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"

      - name: Commit & Push if README changed
        if: ${{ steps.hash_before.outputs.val != steps.hash_after.outputs.val }}
        run: |
          git config --local user.name "kagancansit"
          git config --local user.email "kagancansit@hotmail.com"
          git add README.md
          git commit -m "chore: update README [skip ci]"
          git push